- simulator:
    showGUI: false
    coords:
      lat: 40.63076510273117
      lon: -8.661247560870986
      alt: 8.2
  fleetman:
    id: drone01
    telemetryRateMs: 200
    maxSpeed: 5
    takeoffAltitude: 3
- simulator:
    showGUI: false
    coords:
      lat: 40.630784534320505
      lon: -8.66119919736232
      alt: 8.2
  fleetman:
    id: drone02
    telemetryRateMs: 200
    maxSpeed: 5
    takeoffAltitude: 3
- simulator:
    showGUI: false
    coords:
      lat: 40.63080324621601
      lon: -8.661151782157742
      alt: 8.2
  fleetman:
    id: drone03
    telemetryRateMs: 200
    maxSpeed: 5
    takeoffAltitude: 3