- simulator:
    showGUI: false
    coords:
      lat: 40.680340 
      lon: -8.723144
      alt: 8.2
  fleetman:
    id: drone01
    telemetryRateMs: 200
    maxSpeed: 5
    takeoffAltitude: 3
- simulator:
    showGUI: false
    coords:
      lat: 40.677080 
      lon: -8.724361
      alt: 8.2
  fleetman:
    id: drone02
    telemetryRateMs: 200
    maxSpeed: 5
    takeoffAltitude: 3
- simulator:
    showGUI: false
    coords:
      lat: 40.677763 
      lon: -8.721287
      alt: 8.2
  fleetman:
    id: drone03
    telemetryRateMs: 200
    maxSpeed: 5
    takeoffAltitude: 3
