#all params necessary to define a mission
string sensor_id
string stype
float32 sdist
float32 sgrab_time
float32 sspeed
float32 sother
float32 speriod


# comments in order:
# Unique name
# Czt,lidar,gmc,other
# The distance between parallel flight lines, while sweeping the floor.
# Time required to allow adequate measurement (or sensing) statistics.
# Maximum speed allowed to fly over a sampling location.
# Generic field for the sensor
# Time between individual samples collection.


# all SI units
