droneId: drone01
plotDimension: 500
sensorTopic: /sensors
telemTopic: /telem
rate: 200
environmentTemp: 20
heatSources:
  - coords:
      lat: 40.633400
      lon: -8.660815
    radius: 50
    temp: 60